### ISSUE TITLE
accents are replaced with another character

### ISSUE THREAD

**Issue by pietergent** [mausch/GDataDB#20]
Hi,

With the 0.6 version I noticed that accents in words are replaced. Like for instance "Fernández" becomes "Fern�ndez".
Same thing with Gaëtan, Cédric, Bruyère, ...

Regards,

Pieter

**Comment by pietergent** [comment]
I haven't looked in detail where this goes wrong, but it might be that somewhere when making an url all these special characters must be replaced? I had to do that one day in a portion of code, this might help:

.Replace(" ", "%20").Replace("ï", "%C3%AF").Replace("î", "%C3%AE").Replace("é", "%C3%A9").Replace("è", "%C3%A8").Replace("ê", "%C3%AA").Replace("ë", "%C3%AB").Replace("ö", "%C3%B6").Replace("Ö", "%C3%96").Replace("ô", "%C3%B4").Replace("ç", "%C3%A7").Replace("á", "%C3%A1").Replace("ñ", "%C3%B1")

**Comment by pietergent** [comment]
Reading accents works fine, it's on the update (and maybe also the insert) it is failing

**Comment by mausch** [comment]
Fixed in https://github.com/mausch/GDataDB/commit/dda098f56d7b097dbd0dbaebf5f4d1dc82287747 , released in 0.6.1 https://www.nuget.org/packages/GDataDB/0.6.1

**Comment by pietergent** [comment]
great! seems to work!
thanks a lot!
