### ISSUE TITLE
Importing googles spreadsheet into excel using c#.net

### ISSUE THREAD

**Issue by blue9manish** [mausch/GDataDB#23]
Hi,
I am trying to import google spreadsheet data into excel using c#, i found google api can be best used here for connecting to g data. 
Can you please guide me in writing a procedure here in c# to connect to google spreadsheet and exports its data into excel and similarly import excel data in google spreadsheet.
I did install the google_api_2.0 which is latest version on my system.

Thanks,
Manish

**Comment by mausch** [comment]
Hi, I think you can use the Drive API to do that ( https://www.nuget.org/packages/Google.Apis.Drive.v2/ ).
There's some sample .NET code in https://developers.google.com/drive/v3/web/quickstart/dotnet .
The reference docs are in https://developers.google.com/drive/v2/reference/files/insert

This is however out of the scope of GDataDB, try asking on Stackoverflow.
