### ISSUE TITLE
Reading values with commas

### ISSUE THREAD

**Issue by kevingy** [mausch/GDataDB#24]
I'm reading a Google spreadsheet with financial data. It was only a matter of time before someone entered a value greater than $999.99 into a column that I have been reading into a decimal property in the defined entity. When parsing any number greater than or equal to 1,000.00, Serializer.ConvertFrom() throws an unhandled exception, {"2,210.00 is not a valid value for Decimal."} with an internal exception message of {"Input string was not in a correct format."}. I assume it's the comma. I already had to remove the $ characters from the spreadsheet that were causing the same issue. I'd really rather not have to remove the commas from the spreadsheet as well. (The accountant is already complaining about the missing dollar signs.) Any ideas?

**Comment by mausch** [comment]
GDataDB uses [`Convert.ChangeType`](https://msdn.microsoft.com/en-us/library/dtb69x08%28v=vs.110%29.aspx) under the hood, so this should work: http://stackoverflow.com/questions/3847446/extending-convert-changetype-to-produce-user-defined-types-on-request

**Comment by mausch** [comment]
Otherwise you could have GDataDB map it to a string property and then you'd do your own parsing.

**Comment by kevingy** [comment]
I worked around it another way, but I suspect that management will not like my work-around long term. I'll go the IConvertible route when I need to. Thanks!
